"""Synthetic dot/particle image generator and ground-truth-based evaluation
metrics (IoU, Average Precision, detection rate). Because the ground truth
is generated by us, this tab gives an *exact* benchmark of a segmentation
pipeline's performance -- useful for characterizing sensitivity to noise,
density, and dot size even when no real annotated data exists.
"""
from __future__ import annotations

from typing import Optional, Tuple

import numpy as np
import pandas as pd
from scipy.ndimage import gaussian_filter
from scipy.sparse import coo_matrix
from skimage.draw import disk


def generate_synthetic_dots(
    shape: Tuple[int, int] = (512, 512),
    n_dots: int = 150,
    radius_mean: float = 5.0,
    radius_std: float = 1.5,
    blur_sigma: float = 1.2,
    poisson_scale: float = 1.0,
    gaussian_noise_sigma: float = 5.0,
    background_level: float = 10.0,
    signal_level: float = 200.0,
    seed: Optional[int] = None,
) -> Tuple[np.ndarray, np.ndarray]:
    """Simulate a fluorescence image of round dots/particles with an exact
    known ground-truth instance mask.

    Pipeline: draw solid disks at random positions -> convolve with a
    Gaussian (approximates the microscope's point-spread function) -> add
    Poisson (photon shot) noise -> add Gaussian (electronic read) noise.
    This mirrors the two dominant, physically distinct noise sources in
    real fluorescence microscopy.
    """
    rng = np.random.default_rng(seed)
    gt_mask = np.zeros(shape, dtype=np.int32)
    signal = np.zeros(shape, dtype=np.float64)

    centers_row = rng.uniform(0, shape[0], size=n_dots)
    centers_col = rng.uniform(0, shape[1], size=n_dots)

    label_id = 0
    for row, col in zip(centers_row, centers_col):
        radius = max(1.0, rng.normal(radius_mean, radius_std))
        rr, cc = disk((row, col), radius, shape=shape)
        if rr.size == 0:
            continue
        label_id += 1
        # Later dots painted on top of earlier ones at overlaps -- this
        # intentionally simulates touching/occluding objects.
        gt_mask[rr, cc] = label_id
        signal[rr, cc] = signal_level

    blurred = gaussian_filter(signal, sigma=blur_sigma) + background_level

    # Poisson (shot) noise: sampling at a scaled-up rate and rescaling back
    # lets `poisson_scale` act as an SNR knob (lower = noisier) without
    # changing the mean intensity.
    if poisson_scale > 0:
        blurred = rng.poisson(np.clip(blurred, 0, None) * poisson_scale) / poisson_scale

    noisy = blurred + rng.normal(0, gaussian_noise_sigma, size=shape)
    noisy = np.clip(noisy, 0, None)

    return noisy.astype(np.float32), gt_mask


def _label_overlap_matrix(gt_mask: np.ndarray, pred_mask: np.ndarray) -> np.ndarray:
    """Pixel-overlap contingency table between two label images: rows are
    ground-truth labels, columns are predicted labels (0 = background,
    included so index == label id).
    """
    gt_flat = gt_mask.ravel().astype(np.int64)
    pred_flat = pred_mask.ravel().astype(np.int64)
    n_gt = int(gt_flat.max()) + 1
    n_pred = int(pred_flat.max()) + 1
    overlap = coo_matrix(
        (np.ones(gt_flat.size, dtype=np.int64), (gt_flat, pred_flat)),
        shape=(n_gt, n_pred),
    ).toarray()
    return overlap


def compute_iou_matrix(gt_mask: np.ndarray, pred_mask: np.ndarray) -> np.ndarray:
    """IoU for every (ground-truth, predicted) label pair, background
    (row/col 0) excluded from the result.
    """
    overlap = _label_overlap_matrix(gt_mask, pred_mask)
    gt_areas = overlap.sum(axis=1, keepdims=True)
    pred_areas = overlap.sum(axis=0, keepdims=True)
    union = gt_areas + pred_areas - overlap
    with np.errstate(divide="ignore", invalid="ignore"):
        iou = np.where(union > 0, overlap / union, 0.0)
    return iou[1:, 1:]


def match_at_threshold(iou_matrix: np.ndarray, threshold: float):
    """Greedy one-to-one matching of ground-truth <-> predicted objects,
    highest IoU pairs matched first, subject to ``IoU >= threshold``.

    Returns ``(n_tp, n_fp, n_fn, matched_ious)``.
    """
    n_gt, n_pred = iou_matrix.shape
    candidates = np.argwhere(iou_matrix >= threshold)
    scores = iou_matrix[candidates[:, 0], candidates[:, 1]] if candidates.size else np.array([])
    order = np.argsort(-scores)

    matched_gt, matched_pred, matched_ious = set(), set(), []
    for idx in order:
        i, j = candidates[idx]
        if i in matched_gt or j in matched_pred:
            continue
        matched_gt.add(i)
        matched_pred.add(j)
        matched_ious.append(float(iou_matrix[i, j]))

    tp = len(matched_ious)
    fp = n_pred - len(matched_pred)
    fn = n_gt - len(matched_gt)
    return tp, fp, fn, matched_ious


def evaluate_against_ground_truth(
    gt_mask: np.ndarray,
    pred_mask: np.ndarray,
    thresholds: Optional[np.ndarray] = None,
) -> pd.DataFrame:
    """Precision / recall / F1 / AP across a range of IoU thresholds,
    following the convention used in cell-segmentation benchmarks (e.g.
    Cellpose, StarDist): ``AP(t) = TP / (TP + FP + FN)`` at IoU threshold
    ``t``. Recall at each threshold also serves as the detection rate.
    """
    if thresholds is None:
        thresholds = np.arange(0.5, 1.0, 0.05)

    iou_matrix = compute_iou_matrix(gt_mask, pred_mask)
    rows = []
    for t in thresholds:
        tp, fp, fn, matched_ious = match_at_threshold(iou_matrix, t)
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
        ap = tp / (tp + fp + fn) if (tp + fp + fn) else 0.0
        rows.append(
            {
                "iou_threshold": round(float(t), 2),
                "TP": tp,
                "FP": fp,
                "FN": fn,
                "precision": precision,
                "recall": recall,
                "f1": f1,
                "AP": ap,
                "mean_matched_iou": float(np.mean(matched_ious)) if matched_ious else np.nan,
            }
        )
    return pd.DataFrame(rows)
